### PR TITLE
cleanup CI definition

### PR DESCRIPTION
**Pull request by qno**
I was just looking at the Azure CI definition and there is a lot of redundant instructions.
So I try to clean up and make it more compact.

### CODE REVIEW

**Comment by qno** [comment]
Done - now everything should work as usual!

**Comment by AriaSalvatrice** [comment]
Thank you! I still have no clue how this arcane Azure magickry works, so anything that makes it simpler is welcome.

**Comment by qno** [comment]
It would also be possible to switch CI build to Github workflow, so it gets built on Github CI servers instead on Azure. It is basically already built in and needs no extra setup steps for the repo. And Linux, MacOS and Windows VMs are available. For me the only advantage with Azure is that it supports also unit test reporting with code coverage, etc.

You can just throw a Github workflow definition into a VCV Rack plugin repo on github and all the stuff would be build automatically, so nobody needs anymore to aks for specific platform builds on the VCV Forum.

I could create such a worklow definition based on your Azure definition with Rack Makefile. When I do program VCV stuff I use complete different approach with Conan and CMake, because this manual setup of build environment and that Makefile stuff really sucks.

**Comment by qno** [comment]
OK - I already tested this - here you can see the result so far - https://github.com/qno/AriaVCVModules/actions

**Comment by AriaSalvatrice** [comment]
Neato :D 

Well on my end Azure solves the problem and work fine, so I think I'd rather not swap to something I don't know yet... but it'd definitely be worth documenting the simplest process possible for other devs!

**Pull request merged**
